# Generated by Django 4.2.7 on 2024-04-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Uploads',
            new_name='products',
        ),
    ]
